global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'youtube-bot'
    static_configs:
      - targets: ['youtube-bot:8090']
    metrics_path: '/metrics'
    scheme: 'http'
